parse:
  remove_words:
    - <word>
  remove_lines_with:
    - <word>
    - <sentence>
  stop_word: <word>
  type_map:
    <credit>: Credit
    <transfer>: Transfer
    <debit>: Debit
statement_dir: <dir>
categories:
  <category1>:
    - <target1>
    - <target2>
